# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stripe < Formula
  desc "Stripe CLI utility"
  homepage "https://stripe.com"
  version "1.29.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/stripe/stripe-cli/releases/download/v1.29.0/stripe_1.29.0_mac-os_x86_64.tar.gz"
    sha256 "8145007e79a6601c26070ead3178ba2650349c19a937963bc62ce7247a54bd25"

    def install
      bin.install "stripe"
      rm Dir["#{bin}/{stripe-completion.bash,stripe-completion.zsh}"]
      system bin/"stripe", "completion", "--shell", "bash"
      system bin/"stripe", "completion", "--shell", "zsh"
      bash_completion.install "stripe-completion.bash"
      zsh_completion.install "stripe-completion.zsh"
      (zsh_completion/"_stripe").write <<~EOS
        #compdef stripe
        _stripe () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/stripe-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/stripe/stripe-cli/releases/download/v1.29.0/stripe_1.29.0_mac-os_arm64.tar.gz"
    sha256 "9b3b413822954c7681e158d2a66891f5ed832579c38b5f15b0c0f43fef15ba39"

    def install
      bin.install "stripe"
      rm Dir["#{bin}/{stripe-completion.bash,stripe-completion.zsh}"]
      system bin/"stripe", "completion", "--shell", "bash"
      system bin/"stripe", "completion", "--shell", "zsh"
      bash_completion.install "stripe-completion.bash"
      zsh_completion.install "stripe-completion.zsh"
      (zsh_completion/"_stripe").write <<~EOS
        #compdef stripe
        _stripe () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/stripe-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Stripe CLI! If this is your first time using the CLI, be sure to run `stripe login` first.
    EOS
  end
end
